name: docdoc
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  # state management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  # network
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.3 # in dev_dependencies
  
  # Code generator ( mainly used to used with cubit & retrofit)
  # freezed: ^2.5.7
  # freezed_annotation: ^2.4.4

  # Di
  get_it: ^8.0.0
  injectable: ^2.4.4
  # auto generate code for to and from json by annotation dart
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0 # in dev_dependencies
  # localization
  intl: ^0.19.0
  easy_localization: ^3.0.7
  # Native splash screen
  flutter_native_splash: ^2.4.1
  # flutter svg 
  flutter_svg: ^2.0.10+1
  # flutter plugin for adapting screen and font size.
  flutter_screenutil: ^5.9.3
  # for check Internet
  connectivity_plus: ^6.1.0
  # Functional Programming in Dart allowing you return either <Failure,Success>
  dartz: ^0.10.1
  # firebase core
  firebase_core: ^3.7.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.5
dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  injectable_generator: null
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

