
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Ditrubtion"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --flavor Production -t lib/main_production.dart"
    firebase_app_distribution(
      app: "1:396421235967:android:812c565464e60641ce38ca",
      firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
      # android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
      testers:"gehademad657@gmail.com",
      release_notes: "First Faslane App Distrubtion !!!!!!!!!!",
    )
  end
end
