name: Android Fastlane with Firebase App Distribution Workflow



on:
  push:
    branches:
      - main

jobs:
  Distribute_To_Firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Check out My Repo Code
        uses: actions/checkout@v2

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # You can specify other distributions if needed

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install
        working-directory: android

      - name: Build and Distribute App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
        working-directory: android
